server:
  port: 80
eureka:
  client:
    # 自身不注册进eureka，就是一个客户端
    register-with-eureka: false
    service-url:
      # 把集群中的所有注册中心都加进去
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

ribbon:
  # 指的是建立连接的时间，适用于网络正常情况下，两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
    # feign 日志以什么级别监控那个接口
    com.xinghaol.springcloud.service.PaymentFeignService: debug
