CREATE TABLE `payment`
(
    `id`     BIGINT(20)   NOT NULL AUTO_INCREMENT COMMENT '主键id',
    `serial` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '全局流水号',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = utf8